name: Compile PDFs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile
      run: make resume.pdf

    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: examples
        path: examples/*.pdf
