name: Compile PDFs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Compile
      run: make resume.pdf

    - uses: actions/upload-artifact@v3
      with:
        name: examples
        path: examples/*.pdf
  print_resume_log:
    runs-on: ubuntu-latest
    needs: build  # Specify the dependency on the 'build' job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Resume Log
      run: cat examples/resume.log
